<?php
/**
 * Created by PhpStorm.
 * User: kta
 * Date: 1/17/17
 * Time: 12:37 PM
 */
?>


<div class="pdf_wrapper page1pdf" style="padding-bottom: 40px;">

    <h2 style=" padding: 20px 0;">EXHIBIT "A"</h2>
    <h2 style="padding:0; padding-bottom: 20px; font-weight: normal; text-decoration: underline;">COMPENSATION</h2>

    <div class="pdf_page1_block1" style="text-align: left;">
        During the Part-Time Employment Term: </div>


    <div class="pdf_page1_block1" style="text-align: left;">
       <ol style="padding-left: 60px;">

         <li style="list-style-type: lower-roman; padding-bottom: 20px;">Employee shall be compensated at a rate equal to $ <input type="text"  class="p1_b1_input2n"/>  per TC.</li>
         <li style="list-style-type: lower-roman; padding-bottom: 20px;">

             Compensation shall become due from, and be payable by, Employer only upon
             <br/> <br/>
             (a)&nbsp;&nbsp;&nbsp;Employer’s compensation greater than $100 for its technical component
             connected to an ANS test (“TC”);<br/> <br/>
             (b)&nbsp;&nbsp;&nbsp;TC generated as a direct result of the Employee’s placement of the ANS
             device;<br/> <br/>
             (c)&nbsp;&nbsp;&nbsp;On the 5<sup>th</sup> day of each month following the Employer’s receipt of the TC
             during the prior month.


         </li>

           <li style="list-style-type: lower-roman; padding-bottom: 20px;">(a) Employee shall be required to refund to Employer (or Employer may off-set) any
               compensation paid to Employee for which reimbursement is later denied or recovered
               by any insurance payor, and (b) Employer may reasonably adjust Employee’s
               compensation upon any declining reimbursement rates.</li>

           <li style="list-style-type: lower-roman; padding-bottom: 20px;">Employer shall provide Employee a monthly compensation report reflecting the TC
               generated by Employee, and associated details.</li>

       </ol>



    </div>

    <div class="pdf_page1_block1" style="text-align: left;">
        EXHIBIT A shall <i>not</i> survive termination if Employee violated any federal or state law during
        the Part-Time Employment Term of this Agreement, or violates Section IX G and IX H.
        Notwithstanding the foregoing, section iii (a) and (b) of EXHIBIT A shall survive termination,
        irrespective of reason for termination.
        </div>

</div>


<div class="exhibit_btnwrapper">
    <input type="button" value="Agree">
    <input type="button" value="Disagree">

</div>


